name: Report
on:
  schedule:
    - cron: '15 * * * *'
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'martinfrancois/WAF-AbuseIPDB'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.12
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Report
      run: python main.py
      env:
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
        PEPPER: ${{ secrets.PEPPER }}
        IGNORED_IP_ADDRESSES: ${{ secrets.IGNORED_IP_ADDRESSES }}
